name: Fitbit Workflow

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create environment file
      run: |
        cat << EOF > .env
        # Fitbit environment variables
        FITBIT_AUTH_URI="$FITBIT_AUTH_URI"
        FITBIT_EXPIRES_AT="$FITBIT_EXPIRES_AT"
        FITBIT_REDIRECT_URI="$FITBIT_REDIRECT_URI"
        FITBIT_TOKEN_REQUEST_URI=${{ FITBIT_TOKEN_REQUEST_URI }}
        # Fitbit secrets
        FITBIT_ACCESS_TOKEN=${{ secrets.FITBIT_ACCESS_TOKEN }}
        FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }}
        FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }}
        FITBIT_REFRESH_TOKEN=${{ secrets.FITBIT_REFRESH_TOKEN }}
        EOF
  
    - name: Display .env file contents
      run: cat .env

    - name: Echo Non-Sensitive Environment Variables
      run: |
        echo "FITBIT_AUTH_URI: $FITBIT_AUTH_URI"
        echo "FITBIT_EXPIRES_AT: $FITBIT_EXPIRES_AT"
        echo "FITBIT_REDIRECT_URI: $FITBIT_REDIRECT_URI"
        echo "FITBIT_TOKEN_REQUEST_URI: $FITBIT_TOKEN_REQUEST_URI"

    - name: List All Environment Variables
      run: env

    - name: Build Docker image
      run: docker build -t fitbit-app .

    - name: Run Fitbit Tokens Command
      run: docker run --env-file .env fitbit-app python fitbit.py fitbit-tokens

    - name: Run Fitbit Steps Command
      run: docker run --env-file .env fitbit-app python fitbit.py fitbit-steps

    - name: Upload Fitbit Tokens output to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fitbit-tokens
        path: fitbit_tokens.json
