name: Fitbit Workflow

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create environment file
      run: |
        cat << EOF > .env
        # Fitbit environment variables
        FITBIT_AUTH_URI=${{ vars.FITBIT_AUTH_URI }}
        FITBIT_EXPIRES_AT=${{ vars.FITBIT_EXPIRES_AT }}
        FITBIT_REDIRECT_URI=${{ vars.FITBIT_REDIRECT_URI }}
        FITBIT_TOKEN_REQUEST_URI=${{ vars.FITBIT_TOKEN_REQUEST_URI }}
        # Fitbit secrets
        FITBIT_ACCESS_TOKEN=${{ secrets.FITBIT_ACCESS_TOKEN }}
        FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }}
        FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }}
        FITBIT_REFRESH_TOKEN=${{ secrets.FITBIT_REFRESH_TOKEN }}
        EOF
  
    - name: Display .env file contents
      run: cat .env

    - name: Build Docker image
      run: docker build -t fitbit-app .

    - name: Run Fitbit Tokens Command
      run: docker run --env-file .env -v ${{ github.workspace }}:/app fitbit-app python fitbit.py fitbit-tokens

    - name: Update README
      run: |
        FITBIT_STEPS=$(docker run fitbit-app python fitbit.py fitbit-steps)
        FITBIT_SLEEP=$(docker run fitbit-app python fitbit.py fitbit-sleep)
        sed -i "s/^So far today, I have walked .* steps and slept for .*$/So far today, I have walked $FITBIT_STEPS steps and slept for $FITBIT_SLEEP/" README.md

    - name: Display README.md contents
      run: cat README.md

    - name: Upload Fitbit Tokens output to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fitbit-tokens
        path: fitbit_tokens.json
