name: GitHub Profile README Updater Workflow

on:
  push:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create environment file
      run: |
        cat << EOF > .env
        ### Fitbit environment variables
        FITBIT_AUTH_URI=${{ vars.FITBIT_AUTH_URI }}
        FITBIT_EXPIRES_AT=${{ vars.FITBIT_EXPIRES_AT }}
        FITBIT_REDIRECT_URI=${{ vars.FITBIT_REDIRECT_URI }}
        FITBIT_TOKEN_REQUEST_URI=${{ vars.FITBIT_TOKEN_REQUEST_URI }}
        ### Fitbit secrets
        FITBIT_ACCESS_TOKEN=${{ secrets.FITBIT_ACCESS_TOKEN }}
        FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }}
        FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }}
        FITBIT_REFRESH_TOKEN=${{ secrets.FITBIT_REFRESH_TOKEN }}
        ### Strava environment variables
        STRAVA_AUTH_URI=${{ vars.STRAVA_AUTH_URI }}
        STRAVA_EXPIRES_AT=${{ vars.STRAVA_EXPIRES_AT }}
        STRAVA_REDIRECT_URI=${{ vars.STRAVA_REDIRECT_URI }}
        STRAVA_TOKEN_REQUEST_URI=${{ vars.STRAVA_TOKEN_REQUEST_URI }}
        ### Strava secrets
        STRAVA_ACCESS_TOKEN=${{ secrets.STRAVA_ACCESS_TOKEN }}
        STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN=${{ secrets.STRAVA_REFRESH_TOKEN }}
        EOF

    - name: Get most recent successful run
      id: get-successful-run
      uses: actions/github-script@v7  
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yaml',
            status: 'completed',
          });

          const successfulRun = data.workflow_runs.find(run => run.conclusion === 'success');

          if (!successfulRun) {
            core.setOutput("runId", null);
            core.setOutput("found", false);
          } else {
            core.setOutput("runId", successfulRun.id);
            core.setOutput("found", true);
          }

    - name: Download Fitbit Tokens from GitHub Artifacts
      uses: actions/download-artifact@v4
      with:
        name: fitbit-tokens
        run-id: ${{ steps.get-successful-run.outputs.runId }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.get-successful-run.outputs.found == 'true'
      continue-on-error: true

    - name: Download Strava Tokens from GitHub Artifacts
      uses: actions/download-artifact@v4
      with:
        name: strava-tokens
        run-id: ${{ steps.get-successful-run.outputs.runId }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.get-successful-run.outputs.found == 'true'
      continue-on-error: true

    - name: Echo Workflow Run Information
      run: |
        echo "[INFO] Current Workflow Run ID: $GITHUB_RUN_ID"
        echo "[INFO] Attempting to download artifact from Run ID: ${{ steps.get-successful-run.outputs.runId }}"

    - name: Check download status and notify if failed
      if: failure() && steps.get-successful-run.outputs.found == 'true' # This step runs if the download step failed
      run: |
        echo "[ERROR] Artifact download failed."

    - name: Update .env file with latest tokens data
      run: |
        if [ -f fitbit_tokens.json ]; then
          FITBIT_ACCESS_TOKEN=$(jq -r '.FITBIT_ACCESS_TOKEN' fitbit_tokens.json)
          FITBIT_REFRESH_TOKEN=$(jq -r '.FITBIT_REFRESH_TOKEN' fitbit_tokens.json)
          FITBIT_EXPIRES_AT=$(jq -r '.FITBIT_EXPIRES_AT' fitbit_tokens.json)

          echo "FITBIT_ACCESS_TOKEN=$FITBIT_ACCESS_TOKEN" >> .env
          echo "FITBIT_REFRESH_TOKEN=$FITBIT_REFRESH_TOKEN" >> .env
          echo "FITBIT_EXPIRES_AT=$FITBIT_EXPIRES_AT" >> .env
        else
          echo "[WARN] fitbit_tokens.json not found, skipping .env update."
        fi

        if [ -f strava_tokens.json ]; then
          STRAVA_ACCESS_TOKEN=$(jq -r '.STRAVA_ACCESS_TOKEN' strava_tokens.json)
          STRAVA_REFRESH_TOKEN=$(jq -r '.STRAVA_REFRESH_TOKEN' strava_tokens.json)
          STRAVA_EXPIRES_AT=$(jq -r '.STRAVA_EXPIRES_AT' strava_tokens.json)

          echo "STRAVA_ACCESS_TOKEN=$STRAVA_ACCESS_TOKEN" >> .env
          echo "STRAVA_REFRESH_TOKEN=$STRAVA_REFRESH_TOKEN" >> .env
          echo "STRAVA_EXPIRES_AT=$STRAVA_EXPIRES_AT" >> .env
        else
          echo "[WARN] strava_tokens.json not found, skipping .env update."
        fi

    - name: Build Docker image
      run: docker build -t fitness-cli .

    - name: Run GitHub Profile Tokens commands
      run: |
        docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.fitbit fitbit-tokens
        docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.strava strava-tokens

    - name: Update README
      run: |
        FITBIT_STEPS=$(docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.fitbit fitbit-steps | tr -d '\n')
        FITBIT_SLEEP=$(docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.fitbit fitbit-sleep | tr -d '\n')
        STRAVA_WORKOUT=$(docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.strava strava-latest-workout | awk 'NR==1')
        STRAVA_WORKOUT_TIME=$(docker run --env-file .env -v ${{ github.workspace }}:/app fitness-cli python -m app.strava strava-latest-workout | awk 'NR==2')
        sed -i "s|^- <samp> 🚶🏼‍♂️ Today I have walked .* steps and slept for .* <\/samp><br>$|- <samp> 🚶🏼‍♂️ Today I have walked **$FITBIT_STEPS** steps and slept for **$FITBIT_SLEEP** <\/samp><br>|" README.md
        sed -i "s/^- <samp> 🏋🏼‍♂️ My last workout was \*\*.*\*\* for \*\*.*\*\* <\/samp><br>$/- <samp> 🏋🏼‍♂️ My last workout was **$STRAVA_WORKOUT** for **$STRAVA_WORKOUT_TIME** <\/samp><br>/" README.md
        echo "[INFO] Fitbit Steps: $FITBIT_STEPS"
        echo "[INFO] Fitbit Sleep: $FITBIT_SLEEP"
        echo "[INFO] Strava Workout: $STRAVA_WORKOUT"
        echo "[INFO] Strava Workout Time: $STRAVA_WORKOUT_TIME"

    - name: Display README.md contents
      run: cat README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'o6uoq'
        git config --global user.email 'david@git.id.au'
        git add README.md
        git commit -am "🔄 ci: updating README with health data" || echo "🔄 ci: no changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for token refresh failures
      run: |
        if [ -f fitbit_refresh_failed ]; then
          echo "❌ Fitbit token refresh failed"
          echo "Please re-authenticate Fitbit tokens:"
          echo "Run: python -m app.fitbit fitbit-auth"
          exit 1
        fi

    - name: Upload Fitbit Tokens to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fitbit-tokens
        path: fitbit_tokens.json

    - name: Upload Strava Tokens to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strava-tokens
        path: strava_tokens.json
